import { z } from 'zod';
import { logger } from '../utils/logger.js';
import { providerRouter } from './providers/router.js';
import type { ProviderName, RouterContext } from './providers/types.js';

// Quiz question schema
export const QuizQuestionSchema = z.object({
  question: z.string().min(10, 'Question must be at least 10 characters'),
  options: z.array(z.string()).length(4, 'Must have exactly 4 options'),
  correctAnswer: z.number().min(0).max(3, 'Correct answer must be 0-3'),
  explanation: z.string().optional(),
});

// Module content schema
//
// Char limits relaxed from (500, 15000) to (200, 20000) so non-Latin scripts
// (CJK, Arabic, etc.) don't fail validation by being denser per character.
// The prompt instructs ~500-1500 words, which gives appropriate density for
// the target language; a hard char floor/ceiling is just a safety net.
export const ModuleContentSchema = z.object({
  title: z.string().min(10).max(500, 'Title must be between 10-500 characters'),
  content: z.string().min(200).max(20000, 'Content must be between 200-20000 characters'),
  estimatedTime: z.number().min(5).max(60, 'Estimated time must be between 5-60 minutes'),
  quiz: z.array(QuizQuestionSchema).min(3).max(5, 'Must have 3-5 quiz questions'),
});

export type ModuleContent = z.infer<typeof ModuleContentSchema>;
export type QuizQuestion = z.infer<typeof QuizQuestionSchema>;

/**
 * AIService — thin facade over ProviderRouter.
 *
 * Picks an LLM provider via the router (Gemini / Claude / Qwen) based on
 * tier + region from the request context, generates the module, and returns
 * both the validated content and the provider used (for analytics in the DB).
 */
export class AIService {
  async generateModule(
    topic: string,
    level: 'beginner' | 'intermediate' | 'advanced',
    locale: string,
    ctx: RouterContext,
  ): Promise<{ content: ModuleContent; provider: ProviderName }> {
    logger.info(`Generating module: ${topic} (${level}) [${locale}, tier=${ctx.tier}, region=${ctx.region}]`);
    const { result, providerUsed } = await providerRouter.generate(
      { topic, level, locale },
      ctx,
    );
    logger.info(`Module generated by ${providerUsed}: ${result.title}`);
    return { content: result, provider: providerUsed };
  }

  async testConnection(): Promise<boolean> {
    // Tests the default provider (Gemini); see provider.testConnection() for individual checks
    const { result } = await providerRouter.generate(
      { topic: 'test', level: 'beginner', locale: 'en' },
      { tier: 'default', region: 'global', locale: 'en' },
    ).then((r) => ({ result: r.result }))
      .catch(() => ({ result: null }));
    return !!result;
  }
}

export const aiService = new AIService();
